bunderLikeLion/sellon_backend

- db/initial_setup.sql
- docker-compose.production.yml
- docker-compose.yml
- sample_env
- setup.cfg
- webapp/Dockerfile
- webapp/Dockerfile.production
- webapp/Pipfile
- webapp/Pipfile.lock
- webapp/config/settings/base.py
- webapp/config/settings/development.py
- webapp/config/settings/production.py
- webapp/docker-entrypoint.production.sh
- webapp/docker-entrypoint.sh
아래 명령어를 통해, 도커 컨테이너를 띄우고, 서버를 구동합니다.
도커 세팅은...우리 따로 한번 같이 모여서 해보아요..
```sh
$ docker-compose up -d --build
$ docker-compose -f docker-compose.production.yml up -d --build
```
- docker-compose : https://engineer-mole.tistory.com/221
- docker-compose : https://docs.docker.com/compose/
- 07/20
> dockerize, docker-compose

- webapp/Pipfile
- webapp/Pipfile.lock
- webapp/config/settings/base.py
- djangorestframework 설치
- https://www.django-rest-framework.org/tutorial/quickstart/
- 07/20
> djangorestframework 설치

- webapp/config/settings/development.py
- development 환경에서 sql 로그 추가, 로그를 파일로 저장
- https://ssungkang.tistory.com/entry/Django-Logging-%EC%84%A4%EC%A0%95-%EB%B0%8F-SQL-%EC%BF%BC%EB%A6%AC-%ED%99%95%EC%9D%B8
- 7/28일 회의 후까지
> django logger

- docker-compose.yml
- webapp/Dockerfile
- webapp/Dockerfile.production
- webapp/config/settings/base.py
- webapp/config/settings/development.py
- webapp/config/urls.py
- webapp/config/utils.py
- webapp/user/urls.py
- webapp/user/views.py
- 회원탈퇴 기능 구현 및 url 연결
- https://www.cdrf.co/3.13/rest_framework.generics/DestroyAPIView.html
- 08/01
> feat: 회원탈퇴 기능 구현 및 url 연결

- webapp/config/pagination.py
- webapp/config/urls.py
- webapp/product/serializers.py
- webapp/product/urls.py
- webapp/product/views.py
- Proudct Viewset 구현
- 
- ASAP
> feat: product viewset 구현

- webapp/user/serializers/user_abstract_serializer.py
- webapp/user/urls.py
- webapp/user/views.py
- 다른 User 정보를 조회할 수 있는 API
- 
- ASAP
> feat: 다른 User 정보를 조회할 수 있는 API

- webapp/Pipfile
- webapp/Pipfile.lock
- webapp/config/settings/base.py
chore: install django-jazzmin
- https://django-jazzmin.readthedocs.io/installation/
- ASAP
> chore: install django-jazzmin

- webapp/auction/models/auction.py
- webapp/auction/permissions.py
- webapp/auction/serializers/auction_serializers.py
- webapp/auction/views.py
- webapp/config/serializers/integer_choice_field.py
- auction에 product_id로 상품 추가
- IntegerChoiceField 수정
- 없음
- ASAP
> chore: auction에 product_id로 상품 추가

- webapp/Pipfile
- webapp/Pipfile.lock
- webapp/config/settings/base.py
- webapp/config/urls.py
- webapp/product/serializers/__init__.py
- webapp/product/serializers/product_group_serializer.py
- webapp/product/urls/product.py
- webapp/product/urls/product_groups.py
- webapp/product/views.py
- feat: 내가 제시한 물건 (product_groups/my/?auction_id=) 확인 기능
- 
- ASAP
> feat: 내가 제시한 물건 (product_groups/my/?auction_id=) 확인 기능

- webapp/config/pagination.py
- webapp/config/settings/base.py
- fix: 프론트 요청으로 pagination 수정 (page_size 10->9 로 수정 / count (전체 갯수) 추가)
- 
- ASAP
> fix: 프론트 요청으로 pagination 수정

- webapp/product/models/product_group.py
- product_groups의 auction 정보를 수정할 수 없게 함.
- ASAP
> product_groups의 auction 정보를 수정할 수 없게 함.

- webapp/auction/models/auction.py
- 다른 사람이 올린 상품을 등록하려고 하는 경우의 에러메세지 우선순위를 위로 올렸습니다.
- [유진s QA 시트](https://www.notion.so/bunder/QA-4666d3ba9f36440ea72c114e35117856)
- ASAP
> validation 순서 조정

- webapp/product/views/product_view_set.py
- ordering 기능 추가
- ordering 기본값 최신순
- ASAP
> feat: [get] /products/ OrderFilter

- webapp/auction/admin/auction.py
- webapp/product/models/product_group.py
- webapp/product/serializers/product_group_serializer.py
- previous_object가 None인지 아닌지 확인하는 조건문 추가
- product_groups_serializer에서 auction 필드 read_only로 수정
- 
- ASAP
> Product groups

- webapp/config/authentications.py
- webapp/config/settings/base.py
- SessionAuthentication을 상속 받아 csrf 인증을 해제하는 클래스를 기본으로 설정함
- 
- ASAP
> feat: csrf 토큰 인증 해제

- webapp/Pipfile
- webapp/Pipfile.lock
- webapp/config/settings/base.py
- webapp/config/settings/development.py
- webapp/config/urls.py
- silk 라이브러리 추가, sql 로그 삭제(silk로 확인하면 됨)
- 
- ASAP
> Add django silk

- webapp/auction/views/auction_view_set.py
- webapp/product/serializers/product_abstract_serializer.py
- auctions 목록 API에 관심 경매 유무 포함
- auctions 목록 상에서 각 상품마다 product_category 상세 정보가 바로 나오도록 함.
- 08/09
> auctions 목록 API에 관심 경매 유무 포함 / auctions 목록 상에서 각 상품마다 product_category 상세 정보가 바로 나오도록 함.

- webapp/auction/views/auction_view_set.py
- auction 검색 기능 추가
- https://www.django-rest-framework.org/api-guide/filtering/#searchfilter
- ASAP
> auction 검색 기능 추가

- webapp/auction/urls.py
- webapp/auction/views/__init__.py
- webapp/auction/views/add_product_api_view.py
- webapp/auction/views/remove_product_api_view.py
- product를 경매장에 간단하게 추가/삭제할 수 있는 API
(프론트엔드에서 좀더 쉽게 경매장 API를 접근할 수 있게 했습니다.)
- ASAP
> product를 경매장에 간단하게 추가/삭제할 수 있는 API

- webapp/auction/models/auction.py
- fix: popular 경매에서 끝난 경매는 제외하고 가져옴
- 
- ASAP
> fix: popular 경매에서 끝난 경매는 제외하고 가져옴

- webapp/auction/urls.py
- webapp/auction/views/__init__.py
- webapp/auction/views/all_in_api_view.py
- webapp/product/admin/__init__.py
- webapp/product/admin/product_group_item.py
- all in API 추가
- product_group_item 어드민 추가
- ASAP
> all in API 추가 및 product_group_item 어드민 추가

- webapp/auction/admin/interested_auction.py
- webapp/dealing/admin/dealing.py
- webapp/product/admin/product.py
- webapp/product/admin/product_group.py
- feat: fk인 필드를 admin 에서 linkify 로 감싸서 렌더링
- 
- ASAP
> feat: fk인 필드를 admin 에서 linkify 로 감싸서 렌더링

- webapp/auction/admin/interested_auction.py
- webapp/user/urls.py
- webapp/user/views/user_view.py
- 유저마다 평점 API (GET: /users/user/:id/rating)
- ASAP
> Rating api

- webapp/auction/urls.py
- webapp/auction/views/__init__.py
- webapp/auction/views/auction_view_set.py
- webapp/auction/views/my_auction_api_view.py
- feat: /auctions/my/ 에서 내 옥션만 확인 가능
- 
- ASAP
> feat: /auctions/my/ 에서 내 옥션만 확인 가능

- webapp/user/admin.py
- feat: admin 에서 completed-dealings-count 초기화 할 수 있는 액션 생성
- 
- ASAP
> feat: admin 에서 completed-dealings-count 초기화 할 수 있는 액션 생성

- webapp/auction/admin/auction.py
- feat: 옥션 유찰 시 product와 product_group을 hidden 상태로 변경
- 
- 당장!
> feat: 옥션 유찰 시 product와 product_group을 hidden 상태로 변경
